// Fetches true stored dimensions for every gallery photo via Cloudinary fl_getinfo,
// derives the upright display dimensions + needed bake-rotation, and writes
// src/data/galleryDimensions.ts (keyed by the exact photo `src` URL).
//
// Rotation rule: photos shot in portrait were uploaded as sideways landscape files
// (no EXIF), so a photo tagged `vertical` but stored landscape (w > h) is delivered
// with Cloudinary `a_270` to render upright; its display dims are the swapped dims.
//
// Run: node scripts/fetchGalleryDimensions.mjs

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GALLERIES_DIR = join(__dirname, '..', 'src', 'data', 'galleries');
const OUT_FILE = join(__dirname, '..', 'src', 'data', 'galleryDimensions.ts');
const CONCURRENCY = 10;

/** Extract { src, orientation } from every brace-free object literal in a file. */
function extractPhotos(text) {
  const out = [];
  const objects = text.match(/\{[^{}]*\}/g) || [];
  for (const obj of objects) {
    const srcM = obj.match(/src:\s*['"]([^'"]+)['"]/);
    const orientM = obj.match(/orientation:\s*['"](vertical|horizontal)['"]/);
    if (srcM && orientM) out.push({ src: srcM[1], orientation: orientM[1] });
  }
  return out;
}

/** Build the fl_getinfo URL from a delivery URL (keeps version + path). */
function getInfoUrl(src) {
  const clean = src.split('?')[0];
  return clean.replace('/image/upload/', '/image/upload/fl_getinfo/');
}

async function fetchDims(src) {
  const res = await fetch(getInfoUrl(src), { headers: { Accept: 'application/json' } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const json = await res.json();
  const info = json.input || json.output || json;
  const w = Number(info.width);
  const h = Number(info.height);
  if (!w || !h) throw new Error('missing dimensions');
  return { w, h };
}

async function runPool(items, worker) {
  const results = new Array(items.length);
  let i = 0;
  const runners = Array.from({ length: CONCURRENCY }, async () => {
    while (i < items.length) {
      const idx = i++;
      results[idx] = await worker(items[idx], idx);
    }
  });
  await Promise.all(runners);
  return results;
}

async function main() {
  const files = (await readdir(GALLERIES_DIR)).filter(
    (f) => f.endsWith('.ts') && f !== 'index.ts'
  );

  // Collect unique src -> orientation.
  const bySrc = new Map();
  for (const file of files) {
    const text = await readFile(join(GALLERIES_DIR, file), 'utf8');
    for (const { src, orientation } of extractPhotos(text)) {
      if (!bySrc.has(src)) bySrc.set(src, orientation);
    }
  }

  const entries = [...bySrc.entries()];
  console.log(`Found ${entries.length} unique photos across ${files.length} galleries. Fetching dimensions...`);

  let done = 0;
  let failed = 0;
  const dims = {};

  await runPool(entries, async ([src, orientation]) => {
    try {
      const { w: storedW, h: storedH } = await fetchDims(src);
      const needsRotate = orientation === 'vertical' && storedW > storedH;
      const dispW = needsRotate ? storedH : storedW;
      const dispH = needsRotate ? storedW : storedH;
      dims[src] = needsRotate ? { w: dispW, h: dispH, rotate: 270 } : { w: dispW, h: dispH };
    } catch (err) {
      failed++;
      // Fallback to canonical aspect so layout still works.
      dims[src] = orientation === 'vertical' ? { w: 2, h: 3 } : { w: 3, h: 2 };
      console.warn(`  ! ${src.split('/upload/')[1] || src} -> ${err.message} (using ${orientation} fallback)`);
    }
    done++;
    if (done % 50 === 0) console.log(`  ...${done}/${entries.length}`);
  });

  const sortedKeys = Object.keys(dims).sort();
  const rotatedCount = sortedKeys.filter((k) => dims[k].rotate).length;

  const body = sortedKeys
    .map((k) => {
      const d = dims[k];
      const rot = d.rotate ? `, rotate: ${d.rotate}` : '';
      return `  ${JSON.stringify(k)}: { w: ${d.w}, h: ${d.h}${rot} },`;
    })
    .join('\n');

  const header = `// AUTO-GENERATED by scripts/fetchGalleryDimensions.mjs — do not edit by hand.
// Maps each photo \`src\` to its upright display dimensions. \`rotate\` (degrees) is
// the Cloudinary angle baked at delivery so sideways-stored verticals render upright.

export interface PhotoDimensions {
  w: number;
  h: number;
  rotate?: number;
}

export const galleryDimensions: Record<string, PhotoDimensions> = {
`;

  await writeFile(OUT_FILE, header + body + '\n};\n', 'utf8');
  console.log(`\nWrote ${sortedKeys.length} entries to src/data/galleryDimensions.ts`);
  console.log(`  rotated (a_270): ${rotatedCount} | failed/fallback: ${failed}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
